accounts/urls.py
# WZY
# 干了！
# 2023/07/09 13:45
"""为应用程序accounts定义URL模式"""
from django.urls import path,include
from . import views

app_name = 'accounts'
urlpatterns = [
    #包含默认的身份验证URL
    path('',include('django.contrib.auth.urls')),
    #注册账号页面
    path('register/',views.register,name='register')

]

learning_logs/urls.py
# WZY
# 干了！
# 2023/07/04 12:40
"""定义learning_logs的URL模式"""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    #主页
    path('', views.index, name = 'index'),
    #显示所有主题的页面
    path('topics/', views.topics, name = 'topics' ),
    #特定主题的详细页面
    path('topics/<int:topic_id>', views.topic, name = 'topic'),
    #用于添加新主题的页面
    path('new_topic/', views.new_topic, name = 'new_topic'),
    #用于添加新条目的页面
    path('new_entry/<int:topic_id>/',views.new_entry,name = 'new_entry'),
    #用于编辑主题的页面
    path('edit_topic/<int:topic_id>/',views.edit_topic,name='edit_topic'),
    #用于编辑条目的页面
    path('edit_entry/<int:entry_id>/',views.edit_entry, name = 'edit_entry'),
    #用于删除主题的页面
    path('delete_topic/<int:topic_id>/',views.delete_topic,name='delete_topic'),
    #用于删除条目的页面
    path('delete_entry/<int:entry_id>/',views.delete_entry,name='delete_entry'),

]

ll_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('learning_logs.urls'))

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic (models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200) #设置主题名不能超过200个字符
    date_added = models.DateTimeField(auto_now_add=True) #记忆创建时间
    #添加新属性public,使登录或未登录的用户看到其他用户的公开主题
    public = models.BooleanField(default=False)
    #使主题与用户绑定,用户被删除时其中的主题也会被删除
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry (models.Model):
    """学到的有关某个主题的具体知识(创建条目)"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    #ForeignKey(Topic将每个条目关联到特定的主题,  实参on_delete=models.CASCADE,使删除主题时,同时删除相关联的条目
    text = models.TextField() #条目的字数不受限制
    date_added = models.DateTimeField(auto_now_add=True)
    #按创建顺序呈现条目,并在每个条目旁边放置时间戳.

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回一个表示条目的简单字符串"""
        if len(self.text) <= 50:
            return self.text
        else:
            return f"{self.text[:50]}..." #让__str__方法只返回text的前50个字符

learning_logs/forms.py
# WZY
# 干了！
# 2023/07/07 12:35
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text','public']
        labels = {'text' : '' }

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text' : ''}
        #使文本框的宽度增加到80
        widgets = {'text' : forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render,redirect
from .models import Topic,Entry
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required  #django自带的限制器login_required可以限制未登录的用户访问topic
from django.http import Http404
# Create your views here.

def index(request):
    """学习笔记的主页"""
    return render(request,'learning_logs/index.html')

def topics(request):
    """显示所有的主题"""
    if request.user.is_authenticated:
        #如果用户已登录,就获取其所有主题,以及其他用户的所有公开主题
        topics = Topic.objects.filter(owner=request.user).order_by('date_added')
        #获取不归当前用户所有的其他公开主题
        public_topics = Topic.objects.filter(public=True).exclude(owner=request.user).order_by('date_added')
    else:
        #用户未通过身份验证
        topics = None
        public_topics = Topic.objects.filter(public=True).order_by('date_added')

    context = {'topics' : topics,'public_topics' : public_topics}
    return render(request, 'learning_logs/topics.html', context)


def check_topic_owner(topic,request):
    """核实执行操作的用户是否为该主题的关联用户"""
    if topic.owner != request.user:
        raise Http404



def topic(request,topic_id):
    """显示单个主题及其所有条目"""
    topic = Topic.objects.get(id=topic_id)
    #仅当该主题归该用户所用时,才是显示链接new_entry和edit_entry.
    is_owner = False
    if request.user == topic.owner:
        is_owner = True
    #如果该主题归他人所有,且不是公开的,显示错误页面.
    if (topic.owner != request.user) and (not topic.public):
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic , 'entries': entries,'is_owner' : is_owner}
    return render(request,'learning_logs/topic.html',context)

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据: 创建一个新表单(如果用户的请求不是post)
        form = TopicForm()
    else:
        #请求为post的数据:对数据进行处理
        form = TopicForm(data=request.POST)
        if form.is_valid():
            #检查用户提交的信息是否有效
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            #保存数据后,使用redirect()将用户的浏览器重新定向‘topics’界面
            return redirect('learning_logs:topics')

    context = {'form': form }
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic,request)
    if request.method != 'POST':
        #未提交数据: 创建一个新表单(如果用户的请求不是post)
        form = EntryForm()
    else:
        #如果是请求为post的数据:对数据进行处理
        form = EntryForm(data = request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            #让Django创建一个新条目并赋值给new_entry,但不保存到数据库中
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic',topic_id=topic_id)

    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edit_topic(request,topic_id):
    """编辑既有主题名称"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic,request)

    if request.method != 'POST':
        #初次请求时,使用当前主题填充表单
        form = TopicForm(instance=topic)
    else:
        #post请求提交数据:对数据进行处理
        form = TopicForm(instance=topic,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic',topic_id = topic.id)

    context = {'topic': topic,'form' : form}
    return render(request,'learning_logs/edit_topic.html',context)

@login_required
def edit_entry(request,entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic,request)

    if request.method != 'POST':
        #初次请求,使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        #post请求提交数据: 对数据进行处理
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic',topic_id = topic.id)

    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

@login_required
def delete_topic(request,topic_id):
    """删除既有主题"""
    try:
        topic = Topic.objects.get(id=topic_id, owner=request.user)
    except Topic.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        topic.delete()
        return redirect('learning_logs:topics')

    context = {'topic' : topic}
    return render(request,'learning_logs/delete_topic.html',context)

@login_required
def delete_entry(request,entry_id):
    """删除既有条目"""
    try:
        entry = Entry.objects.get(id=entry_id)
        topic = entry.topic
        topic.owner = request.user
    except Topic.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        entry.delete()
        return redirect('learning_logs:topic',topic_id=topic.id)

    context = {'topic':topic,'entry':entry}
    return render(request,'learning_logs/delete_entry.html',context)

learning_logs/templates/learning_logs/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Learning Log</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'learning_logs:index'%}">
                <img style="direction: rtl" class="learning_log_logo"
                src="{% static 'logo_3.png' %}"
                alt="Logo of this website."
                width="50" height="50">Learning Log</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
             data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
             aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
             <ul class="navbar-nav me-auto mb-2 mb-md-O">
                 <li class="nav-item">
                 <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                 Topics</a></li>
             </ul> <!-- 定义导航栏左侧链接的代码到此结束 -->

             <!-- 与账户相关的链接 -->
             <ul class="navbar-nav ms-auto mb-2 mb-md-O">

                 {% if user.is_authenticated %}
                      <li class="nav-item">
                       <span class="navbar-text me-2">Hello,{{ user.username }}
                       </span></li>
                 {% else %}
                      <li class="nav-item">
                       <a class="nav-link" href="{% url 'accounts:register' %}">
                           Register</a></li>
                      <li class="nav-item">
                       <a class="nav-link" href="{% url 'accounts:login'%}">
                           Log in</a></li>
                 {% endif %}

             </ul> <!-- 与账户相关的链接到此结束 -->

             {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button name="submit" class="btn btn-outline-secondary btn-sm">
                        Log out</button>
                </form>
             {% endif %}

            </div> <!-- 定义导航栏可折叠部分的代码到此结束 -->

        </div> <!-- 定义导航栏容器的代码到此结束 -->
    </nav> <!-- 定义导航栏的代码到此结束 -->

    <!-- 定义页面的主要部分,元素之间的间隔 -->
    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %} {% endblock content %}
        </div>

    </main><!-- 定义页面的主要部分的代码到此结束 -->


</body>
</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h2>删除条目</h2>
{% endblock page_header %}

{% block content %}
<h4>您确定要删除该条目吗？</h4>
<div class="card mb-3">
    <h4 class="card-header">所属主题:{{topic.text}}</h4>
    <div class="card-body">{{ entry.text }}</div>
</div>
<form  method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">确认删除</button>
    <a href="{% url 'learning_logs:topics' %}" class="btn btn-primary">取消</a>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/delete_topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h2>删除主题</h2>
{% endblock page_header %}

{% block content %}

    <h4>您确定要删除主题 "{{ topic.text }}" 吗？</h4>
    <h4>基于该主题所创建的所有条目将被一并删除!</h4>
    <form  method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">确认删除</button>
        <a href="{% url 'learning_logs:topics' %}" class="btn btn-primary">取消</a>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>编辑条目</h2>
<h4>Edit Entry</h4>
{% endblock page_header %}

{% block content %}
 <div class="card">
  <h4 class="card-header">{{topic}}</h4>
  <div class="card-body">
    <form action="{% url 'learning_logs:edit_entry' entry.id%}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="确认修改 &raquo;"%}
    </form>
  </div>
 </div>

{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>编辑主题名称</h2>
<h4>Edit Topic Title</h4>
{% endblock page_header %}

{% block content %}
 <form action="{% url 'learning_logs:edit_topic' topic.id%}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="确认修改 &raquo;"%}
 </form>
{% endblock content%}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% load static %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">记录学习</h1>
            <h2 class="display-3">Trak your learning.</h2>
            <p class="lead">
                制作您自己的学习日志，并列出您正在学习的主题.
                每当您学到有关某个主题的新知识时，请记录下来总结您所学到的内容.</p>

            <p>您可以通过创建主题来记录最近开始接触的新鲜事物,然后通过在该主题下创建具体的条目来记录您的学习进度.</p>
            <p>本网站还提供公开主题功能,您可以在主题的编辑与创建栏中勾选‘public’来分享自己的主题.</p>
            <p>所有的用户均可查看已被公开的主题.</p>
            <p>Make your own Learning Log, and keep a list of the topics
                you're learning about. Whenever you learn something new
                about a topic, make an entry summarizing what you've learned.</p>

            {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg mt-1"
                    href="{% url 'learning_logs:topics' %}">查看已有主题 &raquo;</a>
            {% else %}
                <a class="btn btn-primary btn-lg mt-1"
                    href="{% url 'accounts:register' %}">创建自己的学习日志 &raquo;</a>
                <a class="btn btn-primary btn-lg  mt-1"
                    href="{% url 'learning_logs:topics' %}">浏览公开的主题 &raquo;</a>
            {% endif %}
        </div>
    </div>

{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>新条目</h2>
<h5>New Entry</h5>
{% endblock page_header %}

{% block content %}

  <div class="card ">
    <h4 class="card-header"
        href="{% url 'learning_logs:topic' topic.id %}" >{{ topic }}
    </h4>
    <div class="card-body">
      <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      {% bootstrap_form form %}
      {% bootstrap_button button_type="submit" content="添加 &raquo;"%}
      </form>
    </div>
  </div>


{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2> 添加新主题 </h2>
    <h5> New Topic </h5>
{% endblock page_header %}

{% block content %}

<form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="添加 &raquo;"%}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h2>{{ topic.text }}
    {% if is_owner %}
        <a class="btn btn-primary btn-sm mb-6 mt-1 "
           href="{% url 'learning_logs:edit_topic' topic.id %}">
            编辑主题 &raquo;</a>
        <a class="btn btn-danger btn-sm mb-6 mt-1"
            href="{% url 'learning_logs:delete_topic' topic.id %}">
            删除主题 &raquo;</a>
    {% endif %}
</h2>
{% endblock page_header %}

{% block content %}

{% if is_owner %}
    <p>
        <a class="btn btn-primary  mt-1"
           href="{% url 'learning_logs:new_entry' topic.id %}">添加新的条目 &raquo;</a>
    </p>
{% endif %}


<ul>
    {% for entry in entries %}
        <div class="card mb-3">
            <!-- 包含时间戳和编辑链接的标题 -->
            <h4 class="card-header">
                {{entry.date_added|date:'M d, Y H:i'}}
                {% if is_owner %}
                    <a class="btn btn-primary btn-sm " href="{% url 'learning_logs:edit_entry' entry.id %}">
                        编辑</a>
                    <a class="btn btn-danger btn-sm " href="{% url 'learning_logs:delete_entry' entry.id %}">
                        删除</a>
                {% endif %}
            </h4>
            <!-- 包含条目文本的正文 -->
            <div class="card-body">{{ entry.text|linebreaks }}</div>
        </div>
    {% empty %}
        <p>此主题下还没有条目.(There are no entries for this topic yet.)</p>
    {% endfor %}


</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h1>主题</h1>
<h5>Topics</h5>
{% endblock page_header %}

{% block content %}

<!-- 仅当用户已登录时显示 ‘我的主题’ -->
{% if user.is_authenticated %}
  <ul class="list-group border-bottom pb-2 mb-4">
    <h5>我的主题</h5>
    {% for topic in topics %}
      <li class="list-group-item border-0">
        <a href="{% url 'learning_logs:topic' topic.id %}"
           style="font-size: 20px">
        {{ topic.text }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">您还没有添加任何主题.(No topics have been added yet.)</li>
    {% endfor %}
  </ul>
{% endif %}
<a class="btn btn-primary  mt-0 pb-2" href=
        "{% url 'learning_logs:new_topic' %}">添加新主题 &raquo;</a>


<ul class="list-group border-bottom mt-5 pb-2 mb-4">
  <h5>公开的主题</h5>
  {% for topic in public_topics %}
    <li class="list-group-item border-0">
      <a href="{% url 'learning_logs:topic' topic.id %}" style="font-size: 20px">{{ topic.text }}</a>
      <p>--by: {{topic.owner}}</p>
    </li>
  {% empty %}
    <li class="list-group-item border-0">
      当前还没有用户公开主题.(No users have posted any public topics yet.)</li>
  {% endfor %}
</ul>


{% endblock content %}